### PR TITLE
Add variance estimator

### PR DESCRIPTION
**Pull request by mburhanpurkar**

### CODE REVIEW

**Comment by kmsmith137** [comment]
Line 53: xrange(0, len(intensity), self.v1_chunk)

Shouldn't the second argument be either self.nt_chunk or equivalently intensity.shape[1]?
(Note that len(intensity) returns intensity.shape[0] or equivalently self.nfreq)

Line 63: np.append(np.median(...))

Does this line implicitly assuming that np.median() ignores nan's when calculating the median of an array?  When I tested this I got unpredictable results, e.g:
```
import numpy as np

def nanvec(n):
    """Returns length-n vector containing nan's"""
    return np.zeros(n) / np.zeros(n)

# returns 4.5 as expected
print np.median(np.arange(10))

# returns 7.0, not 4.5 as expected!
print np.median(np.concatenate((np.arange(10),nanvec(5))))
```
In general nan's behave counterintuitively so I'd recommend avoiding using them to represent invalid values!  Some possible alternatives:
  - numpy "MaskedArrays" (defined in the numpy.ma module)
  - defining a parallel boolean array to keep track of which v1 elements are valid
  - representing invalid values by variance=0

Line 79: The np.interp(...) one-liner is very elegant!  Here are some corner cases which came to mind, are these cases ok?
  - only one non-nan element in the array
  - array begins (or ends) with a sequence of nan's, so that interp() is trying to extrapolate instead of interpolate.  in this case maybe it makes most sense to set the variance estimate to zero for these time values?


Minor nitpick/question: self.iv1 doesn't need to be an array, since its value is the same for all frequency channels, no?

Suggest making the output filename a constructor argument (but it could default to None, meaning that the current strftime()-based logic is used to initialize the filename)

**Comment by mburhanpurkar** [comment]
Loop bug fixed, updated nan convention to zeros (I read that the masked arrays were slow, so I figured zeros would work best), and added an fname constructor argument.

For the interp edge cases, in the case of one non-zero element, interp will make everything of the same value as the non-zero element. In the second case, interp just uses the closest value available. Perhaps I should add another check for if num_nonzero < 0.25 * num_output_samples, output all zeros for that frequency here? 

Hm, I am not sure if there is a good way to replace iv1 with a single number because the for loop  completes each nt_chunk for a frequency before moving on to the next one (so v2 may written in the middle of an nt_chunk for a particular frequency, but we would have to start back from the beginning of the nt_chunk for the next frequency), though I'm sure there is a way to do this! I'll think about it...

**Comment by kmsmith137** [comment]
Oh I see - in that case don't worry about making iv1 a scalar!

**Comment by kmsmith137** [comment]
The (num_nonzero < 0.25 * num_output_samples) test you proposed makes
general sense to me - the test should only fail if a channel is RFI-masked
most of the time, in which case it probably makes most sense to consider
the variance estimate for that channel unreliable.

Everything looks good to me, I merged it to master!  (No need to put this
on a devel branch since adding a new transform is a backwards-compatible
change)

**Pull request merged**
